spring:
  application:
    name: estabelecimento-saude
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:estabelecimento-saude;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=MySQL;
    username: admin
    password: estabelecimento-saude
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  messages:
    encoding: ISO-8859-1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  security:
#    user:
#      name: admin
#      password: 49ff1076-cd01-4199-8297-d2e8a25e6a0d
server:
  servlet:
    context-path: /estabelecimento-saude
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: estabelecimento-saude